# Generated by Django 4.2.30 on 2026-09-03 03:18

import apps.homework.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.homework.models.homework_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt']), apps.homework.models.validate_attachment_size]),
        ),
    ]
