# Generated by Django 4.2.30 on 2026-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='student_class',
            field=models.IntegerField(blank=True, choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10')], help_text='Null = All Classes', null=True),
        ),
    ]
