# Generated by Django 4.2.30 on 2026-08-27 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('student_class', models.IntegerField(choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10')])),
                ('roll', models.IntegerField()),
                ('ssc_session', models.IntegerField(help_text='Year when student will be in Class 10+1 (e.g., 27 for 2027)')),
                ('payment_start_month', models.IntegerField(default=1, help_text='Month to start collecting fees (1-12)')),
                ('payment_start_year', models.IntegerField(default=2026, help_text='Year to start collecting fees')),
                ('password', models.CharField(help_text='Auto-generated, teacher can reset', max_length=128)),
                ('address', models.TextField(blank=True)),
                ('parent_name', models.CharField(blank=True, max_length=100)),
                ('parent_phone', models.CharField(blank=True, max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='batches.batch')),
            ],
            options={
                'db_table': 'students_student',
                'ordering': ['student_class', 'roll'],
                'unique_together': {('student_class', 'roll')},
            },
        ),
    ]
