# Generated by Django 4.2.30 on 2026-09-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_hash_student_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(help_text="Hashed with Django's password hasher; use set_student_password()", max_length=128),
        ),
    ]
